export const HEADERS = ['name', 'age', 'email', 'phone', 'address'];

export const CUSTOMER_DATA = [
  {
    name: 'John Doe',
    age: 28,
    email: 'john.doe@example.com',
    phone: '555-0134',
    address: '123 Main St, Springfield, IL',
  },
  {
    name: 'Jane Smith',
    age: 34,
    email: 'jane.smith@example.com',
    phone: '555-0245',
    address: '456 Oak Ave, Denver, CO',
  },
  {
    name: 'Alice Brown',
    age: 23,
    email: 'alice.brown@example.com',
    phone: '555-0356',
    address: '789 Pine Rd, Austin, TX',
  },
  {
    name: 'Bob Johnson',
    age: 45,
    email: 'bob.johnson@example.com',
    phone: '555-0467',
    address: '101 Maple St, Seattle, WA',
  },
  {
    name: 'Emily Davis',
    age: 30,
    email: 'emily.davis@example.com',
    phone: '555-0578',
    address: '202 Birch Ln, Miami, FL',
  },
  {
    name: 'Michael Wilson',
    age: 39,
    email: 'michael.wilson@example.com',
    phone: '555-0689',
    address: '303 Elm St, Portland, OR',
  },
  {
    name: 'Sarah Taylor',
    age: 27,
    email: 'sarah.taylor@example.com',
    phone: '555-0790',
    address: '404 Cedar Ct, Phoenix, AZ',
  },
  {
    name: 'David Lee',
    age: 50,
    email: 'david.lee@example.com',
    phone: '555-0812',
    address: '505 Walnut Dr, Chicago, IL',
  },
  {
    name: 'Linda Martinez',
    age: 33,
    email: 'linda.martinez@example.com',
    phone: '555-0923',
    address: '606 Chestnut Blvd, Dallas, TX',
  },
  {
    name: 'James White',
    age: 41,
    email: 'james.white@example.com',
    phone: '555-1034',
    address: '707 Spruce St, Atlanta, GA',
  },
  {
    name: 'Barbara Harris',
    age: 36,
    email: 'barbara.harris@example.com',
    phone: '555-1145',
    address: '808 Hickory Ln, Raleigh, NC',
  },
  {
    name: 'Robert Clark',
    age: 29,
    email: 'robert.clark@example.com',
    phone: '555-1256',
    address: '909 Redwood Rd, Boise, ID',
  },
  {
    name: 'Jennifer Lewis',
    age: 24,
    email: 'jennifer.lewis@example.com',
    phone: '555-1367',
    address: '111 Aspen St, Columbus, OH',
  },
  {
    name: 'William Walker',
    age: 48,
    email: 'william.walker@example.com',
    phone: '555-1478',
    address: '222 Magnolia Ave, Nashville, TN',
  },
  {
    name: 'Susan Hall',
    age: 38,
    email: 'susan.hall@example.com',
    phone: '555-1589',
    address: '333 Poplar Blvd, Boston, MA',
  },
  {
    name: 'Joseph Allen',
    age: 26,
    email: 'joseph.allen@example.com',
    phone: '555-1600',
    address: '444 Cypress Ct, San Diego, CA',
  },
  {
    name: 'Margaret Young',
    age: 35,
    email: 'margaret.young@example.com',
    phone: '555-1711',
    address: '555 Sycamore St, Kansas City, MO',
  },
  {
    name: 'Charles Hernandez',
    age: 31,
    email: 'charles.hernandez@example.com',
    phone: '555-1822',
    address: '666 Fir Ln, Salt Lake City, UT',
  },
  {
    name: 'Dorothy King',
    age: 40,
    email: 'dorothy.king@example.com',
    phone: '555-1933',
    address: '777 Palm Dr, Tampa, FL',
  },
  {
    name: 'Thomas Wright',
    age: 37,
    email: 'thomas.wright@example.com',
    phone: '555-2044',
    address: '888 Olive St, New Orleans, LA',
  },
  {
    name: 'Nancy Lopez',
    age: 32,
    email: 'nancy.lopez@example.com',
    phone: '555-2155',
    address: '999 Dogwood Ave, San Antonio, TX',
  },
  {
    name: 'Daniel Hill',
    age: 46,
    email: 'daniel.hill@example.com',
    phone: '555-2266',
    address: '123 Juniper Blvd, Minneapolis, MN',
  },
  {
    name: 'Karen Scott',
    age: 42,
    email: 'karen.scott@example.com',
    phone: '555-2377',
    address: '234 Maple Ct, Baltimore, MD',
  },
  {
    name: 'Matthew Green',
    age: 28,
    email: 'matthew.green@example.com',
    phone: '555-2488',
    address: '345 Pine Ave, Omaha, NE',
  },
  {
    name: 'Betty Adams',
    age: 43,
    email: 'betty.adams@example.com',
    phone: '555-2599',
    address: '456 Oak Dr, Baton Rouge, LA',
  },
  {
    name: 'Donald Baker',
    age: 47,
    email: 'donald.baker@example.com',
    phone: '555-2600',
    address: '567 Birch Blvd, Fresno, CA',
  },
  {
    name: 'Helen Nelson',
    age: 30,
    email: 'helen.nelson@example.com',
    phone: '555-2711',
    address: '678 Elm St, Albuquerque, NM',
  },
  {
    name: 'George Carter',
    age: 33,
    email: 'george.carter@example.com',
    phone: '555-2822',
    address: '789 Cedar Ave, Richmond, VA',
  },
  {
    name: 'Sandra Mitchell',
    age: 39,
    email: 'sandra.mitchell@example.com',
    phone: '555-2933',
    address: '890 Walnut Rd, Anchorage, AK',
  },
  {
    name: 'Kenneth Perez',
    age: 29,
    email: 'kenneth.perez@example.com',
    phone: '555-3044',
    address: '901 Chestnut St, Madison, WI',
  },
  {
    name: 'Carol Roberts',
    age: 31,
    email: 'carol.roberts@example.com',
    phone: '555-3155',
    address: '123 Poplar Ln, Des Moines, IA',
  },
  {
    name: 'Steven Turner',
    age: 44,
    email: 'steven.turner@example.com',
    phone: '555-3266',
    address: '234 Hickory Blvd, Reno, NV',
  },
  {
    name: 'Ruth Phillips',
    age: 36,
    email: 'ruth.phillips@example.com',
    phone: '555-3377',
    address: '345 Redwood Ct, Spokane, WA',
  },
  {
    name: 'Edward Campbell',
    age: 38,
    email: 'edward.campbell@example.com',
    phone: '555-3488',
    address: '456 Aspen Dr, Birmingham, AL',
  },
  {
    name: 'Maria Parker',
    age: 41,
    email: 'maria.parker@example.com',
    phone: '555-3599',
    address: '567 Magnolia St, Tulsa, OK',
  },
  {
    name: 'Brian Evans',
    age: 27,
    email: 'brian.evans@example.com',
    phone: '555-3700',
    address: '678 Fir Ave, Little Rock, AR',
  },
  {
    name: 'Lisa Edwards',
    age: 34,
    email: 'lisa.edwards@example.com',
    phone: '555-3811',
    address: '789 Sycamore Rd, Wichita, KS',
  },
  {
    name: 'Ronald Collins',
    age: 45,
    email: 'ronald.collins@example.com',
    phone: '555-3922',
    address: '890 Cypress Blvd, Fort Wayne, IN',
  },
  {
    name: 'Karen Stewart',
    age: 26,
    email: 'karen.stewart@example.com',
    phone: '555-4033',
    address: '901 Juniper Ln, Grand Rapids, MI',
  },
  {
    name: 'Anthony Sanchez',
    age: 40,
    email: 'anthony.sanchez@example.com',
    phone: '555-4144',
    address: '123 Olive St, Greensboro, NC',
  },
  {
    name: 'Donna Morris',
    age: 35,
    email: 'donna.morris@example.com',
    phone: '555-4255',
    address: '234 Dogwood Dr, Lubbock, TX',
  },
  {
    name: 'Mark Rogers',
    age: 43,
    email: 'mark.rogers@example.com',
    phone: '555-4366',
    address: '345 Palm Ave, Aurora, CO',
  },
  {
    name: 'Michelle Reed',
    age: 28,
    email: 'michelle.reed@example.com',
    phone: '555-4477',
    address: '456 Olive Blvd, Tallahassee, FL',
  },
  {
    name: 'Kevin Cook',
    age: 37,
    email: 'kevin.cook@example.com',
    phone: '555-4588',
    address: '567 Spruce Rd, Birmingham, AL',
  },
  {
    name: 'Laura Morgan',
    age: 33,
    email: 'laura.morgan@example.com',
    phone: '555-4699',
    address: '678 Chestnut Ct, Lexington, KY',
  },
  {
    name: 'Jason Bell',
    age: 32,
    email: 'jason.bell@example.com',
    phone: '555-4700',
    address: '789 Palm St, Providence, RI',
  },
  {
    name: 'Amy Murphy',
    age: 30,
    email: 'amy.murphy@example.com',
    phone: '555-4811',
    address: '890 Hickory Ave, Boise, ID',
  },
  {
    name: 'Eric Bailey',
    age: 36,
    email: 'eric.bailey@example.com',
    phone: '555-4922',
    address: '901 Oak Rd, Mesa, AZ',
  },
  {
    name: 'Rebecca Rivera',
    age: 38,
    email: 'rebecca.rivera@example.com',
    phone: '555-5033',
    address: '123 Cedar Blvd, Sioux Falls, SD',
  },
  {
    name: 'Frank Cooper',
    age: 39,
    email: 'frank.cooper@example.com',
    phone: '555-5144',
    address: '234 Walnut Ln, Toledo, OH',
  },
];
